name: Build/Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        OS: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install autopoint, gettext, and cal for Linux (omit texinfo).
        if: runner.os == 'Linux'
        run: |
          sudo apt install autopoint gettext ncal
          sudo apt remove texinfo
      - name: Install autotools, gettext, and libssl for macOS (omit texinfo).
        if: runner.os == 'macOS'
        run: |
          brew install autoconf automake libtool
      - name: Configure ed for Linux.
        if: runner.os == 'Linux'
        run: |
         ./autogen.sh
         ./configure --enable-all-extensions --with-included-regex
      - name: Configure ed for macOS.
        if: runner.os == 'macOS'
        run: |
         ./autogen.sh
         ./configure --enable-all-extensions --with-included-regex LDFLAGS=-L/opt/homebrew/Cellar/openssl@3/3.3.0/lib
      - name: Build ed.
        run: |
          make
      - name: Build and run ed testsuite.
        run: |
          make check # || find testsuite/testsuite.dir -name '*.log' -exec cat {} \+
